services:
  python:
    build: .
    working_dir: /eureka
    volumes:
      - ../eureka:/eureka

  web:
    image: uclalibrary/ursus
    platform: linux/amd64  # set up arm64 build but it still won't pull
    hostname: ursus
    depends_on:
      - db
      - solr
    env_file:
      - ./dotenv.sample
    environment:
      DATABASE_HOST: db
      SOLR_URL: http://solr:8983/solr/ursus
      SOLR_TEST_URL: http://solr_test:8983/solr/ursus
    ports:
      - "127.0.0.1:3000:3000"
    working_dir: /ursus

  db:
    image: mysql:5.6
    platform: linux/amd64
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  solr:
    image: uclalibrary/solr-ursus:8
    ports:
      - '127.0.0.1:8983:8983'
    volumes:
      - solr_data:/var/solr/data


  solr_test:
    image: uclalibrary/solr-ursus:8
    ports:
      - '127.0.0.1:8985:8983'


volumes:
  mysql_data:
  solr_data: