name: Run CI Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEFAULT_PYTHON_VERSION: 3.11

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - run: pip install black
      - run: black --check .

  pytest:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    env:
      SOLR_URL: http://127.0.0.1:8983/solr/californica
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose
      - run: docker-compose up --detach solr
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --only main,test
      - run: poetry run pytest

  check_labels:
    name: Check labels
    needs: [draft-release]  # for autotagger
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  draft-release:
    needs: [pytest]
    permissions:
      contents: write # for release-drafter/release-drafter to create a github release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.1.0
        with:
          config-name: configs/release-drafter.yml
          latest: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
          publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
