name: Build and Release

on:
  release:
    types: [published]

env:
  DEFAULT_PYTHON_VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: 'poetry'

      - name: Set Up Poetry
        run: |
          poetry self add poetry-git-version-plugin
          poetry install --only main
          poetry git-version

      - run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
